import React from 'react';
import { FormattedMessage } from 'react-intl';

export const provinces = [
  { value: 'AB', label: <FormattedMessage id="provinces.ab" /> },
  { value: 'BC', label: <FormattedMessage id="provinces.bc" /> },
  { value: 'MB', label: <FormattedMessage id="provinces.mb" /> },
  { value: 'NB', label: <FormattedMessage id="provinces.nb" /> },
  { value: 'NL', label: <FormattedMessage id="provinces.nl" /> },
  { value: 'NS', label: <FormattedMessage id="provinces.ns" /> },
  { value: 'NT', label: <FormattedMessage id="provinces.nt" /> },
  { value: 'NU', label: <FormattedMessage id="provinces.nu" /> },
  { value: 'ON', label: <FormattedMessage id="provinces.on" /> },
  { value: 'PE', label: <FormattedMessage id="provinces.pe" /> },
  { value: 'QC', label: <FormattedMessage id="provinces.qc" /> },
  { value: 'SK', label: <FormattedMessage id="provinces.sk" /> },
  { value: 'YT', label: <FormattedMessage id="provinces.yt" /> },
];

export const statuses = [
  { value: 'immigrant', label: <FormattedMessage id="status.immigrant" /> },
  { value: 'refugee', label: <FormattedMessage id="status.refugee" /> },
  { value: 'resident', label: <FormattedMessage id="status.pr" /> },
  { value: 'citizen', label: <FormattedMessage id="status.citizen" /> },
];

export const genders = [
  { value: 'male', label: <FormattedMessage id="male" /> },
  { value: 'female', label: <FormattedMessage id="female" /> },
  { value: 'other', label: <FormattedMessage id="other" /> },
];

export const relationshipStatuses = [
  { value: 'married', label: <FormattedMessage id="relationship.married" /> },
  { value: 'single', label: <FormattedMessage id="relationship.single" /> },
  { value: 'divorced', label: <FormattedMessage id="relationship.divorced" /> },
  { value: 'widowed', label: <FormattedMessage id="relationship.widowed" /> },
];

export const joiningReasons = [
  { value: 'help', label: <FormattedMessage id="join.help" /> },
  { value: 'findJob', label: <FormattedMessage id="join.findjob" /> },
];

export const languageLevels = [
  { value: 'none', label: <FormattedMessage id="levels.none" /> },
  { value: 'beginner', label: <FormattedMessage id="levels.beg" /> },
  { value: 'intermediate', label: <FormattedMessage id="levels.int" /> },
  { value: 'advanced', label: <FormattedMessage id="levels.adv" /> },
];

export const relations = [
  { value: 'daughter', label: <FormattedMessage id="relations.daughter" /> },
  { value: 'son', label: <FormattedMessage id="relations.son" /> },
  { value: 'mother', label: <FormattedMessage id="relations.mom" /> },
  { value: 'father', label: <FormattedMessage id="relations.dad" /> },
  { value: 'brother', label: <FormattedMessage id="relations.bro" /> },
  { value: 'sister', label: <FormattedMessage id="relations.sis" /> },
];

export const jobStatuses = [
  { value: 'fulltime', label: <FormattedMessage id="job.full" /> },
  { value: 'parttime', label: <FormattedMessage id="job.part" /> },
  { value: 'unemployed', label: <FormattedMessage id="job.unemployed" /> },
  { value: 'student', label: <FormattedMessage id="job.student" /> },
];

export const lookingForJobOptions = [
  { value: 'true', label: <FormattedMessage id="yes" /> },
  { value: 'false', label: <FormattedMessage id="no" /> },
];

export const educationLevels = [
  { value: 'earlyChildhood', label: <FormattedMessage id="education.ec" /> },
  { value: 'elementary', label: <FormattedMessage id="education.elem" /> },
  { value: 'intermediate', label: <FormattedMessage id="education.int" /> },
  { value: 'secondary', label: <FormattedMessage id="education.sec" /> },
  { value: 'trade', label: <FormattedMessage id="education.trade" /> },
  { value: 'cegep', label: <FormattedMessage id="education.cegep" /> },
  { value: 'bachelors', label: <FormattedMessage id="education.bach" /> },
  { value: 'masters', label: <FormattedMessage id="education.mast" /> },
  { value: 'doctorate', label: <FormattedMessage id="education.doc" /> },
];

export const proficiencyExaminations = [
  { value: 'ielts', label: 'IELTS' },
  { value: 'french', label: <FormattedMessage id="french" /> },
];

export const organizationTypes = [
  { value: 'FDRL', label: <FormattedMessage id="org.fdrl" /> },
  { value: 'NGOV', label: <FormattedMessage id="org.ngov" /> },
  { value: 'PROV', label: <FormattedMessage id="org.prov" /> },
];

export const familyObject = {
  age: '', gender: '', relation: '', relationshipStatus: '',
};

export const workObject = {
  title: '', company: '', years: '',
};

export const langObject = {
  name: '', writingLevel: '', speakingLevel: '',
};

export const countries = [ 
  {value: "Afghanistan", label: <FormattedMessage id= "countries.AF"/>},
  {value: "Albania", label: <FormattedMessage id= "countries.AL"/>},
  {value: "Algeria", label: <FormattedMessage id= "countries.DZ"/>},
  {value: "Andorra", label: <FormattedMessage id= "countries.AD"/>},
  {value: "Angola", label: <FormattedMessage id= "countries.AO"/>},
  {value: "Antigua and Barbuda", label: <FormattedMessage id= "countries.AG"/>},
  {value: "Argentina", label: <FormattedMessage id= "countries.AR"/>},
  {value: "Armenia", label: <FormattedMessage id= "countries.AM"/>},
  {value: "Australia", label: <FormattedMessage id= "countries.AU"/>},
  {value: "Austria", label: <FormattedMessage id= "countries.AT"/>},
  {value: "Azerbaijan", label: <FormattedMessage id= "countries.AZ"/>},
  {value: "Bahamas", label: <FormattedMessage id= "countries.BS"/>},
  {value: "Bahrain", label: <FormattedMessage id= "countries.BH"/>},
  {value: "Bangladesh", label: <FormattedMessage id= "countries.BD"/>},
  {value: "Barbados", label: <FormattedMessage id= "countries.BB"/>},
  {value: "Belarus", label: <FormattedMessage id= "countries.BY"/>},
  {value: "Belgium", label: <FormattedMessage id= "countries.BE"/>},
  {value: "Belize", label: <FormattedMessage id= "countries.BZ"/>},
  {value: "Benin", label: <FormattedMessage id= "countries.BJ"/>},
  {value: "Bhutan", label: <FormattedMessage id= "countries.BT"/>},
  {value: "Bolivia (Plurinational State of)", label: <FormattedMessage id= "countries.BO"/>},
  {value: "Bosnia and Herzegovina", label: <FormattedMessage id= "countries.BA"/>},
  {value: "Botswana", label: <FormattedMessage id= "countries.BW"/>},
  {value: "Brazil", label: <FormattedMessage id= "countries.BR"/>},
  {value: "Brunei Darussalam", label: <FormattedMessage id= "countries.BN"/>},
  {value: "Bulgaria", label: <FormattedMessage id= "countries.BG"/>},
  {value: "Burkina Faso", label: <FormattedMessage id= "countries.BF"/>},
  {value: "Burundi", label: <FormattedMessage id= "countries.BI"/>},
  {value: "Cabo Verde", label: <FormattedMessage id= "countries.CV"/>},
  {value: "Cambodia", label: <FormattedMessage id= "countries.KH"/>},
  {value: "Cameroon", label: <FormattedMessage id= "countries.CM"/>},
  {value: "Canada", label: <FormattedMessage id= "countries.CA"/>},
  {value: "Central African Republic", label: <FormattedMessage id= "countries.CF"/>},
  {value: "Chad", label: <FormattedMessage id= "countries.TD"/>},
  {value: "Chile", label: <FormattedMessage id= "countries.CL"/>},
  {value: "China", label: <FormattedMessage id= "countries.CN"/>},
  {value: "Colombia", label: <FormattedMessage id= "countries.CO"/>},
  {value: "Comoros", label: <FormattedMessage id= "countries.KM"/>},
  {value: "Congo", label: <FormattedMessage id= "countries.CG"/>},
  {value: "Congo, Democratic Republic of the", label: <FormattedMessage id= "countries.CD"/>},
  {value: "Costa Rica", label: <FormattedMessage id= "countries.CR"/>},
  {value: "Côte d'Ivoire", label: <FormattedMessage id= "countries.CI"/>},
  {value: "Croatia", label: <FormattedMessage id= "countries.HR"/>},
  {value: "Cuba", label: <FormattedMessage id= "countries.CU"/>},
  {value: "Cyprus", label: <FormattedMessage id= "countries.CY"/>},
  {value: "Czechia", label: <FormattedMessage id= "countries.CZ"/>},
  {value: "Denmark", label: <FormattedMessage id= "countries.DK"/>},
  {value: "Djibouti", label: <FormattedMessage id= "countries.DJ"/>},
  {value: "Dominica", label: <FormattedMessage id= "countries.DM"/>},
  {value: "Dominican Republic", label: <FormattedMessage id= "countries.DO"/>},
  {value: "Ecuador", label: <FormattedMessage id= "countries.EC"/>},
  {value: "Egypt", label: <FormattedMessage id= "countries.EG"/>},
  {value: "El Salvador", label: <FormattedMessage id= "countries.SV"/>},
  {value: "Equatorial Guinea", label: <FormattedMessage id= "countries.GQ"/>},
  {value: "Eritrea", label: <FormattedMessage id= "countries.ER"/>},
  {value: "Estonia", label: <FormattedMessage id= "countries.EE"/>},
  {value: "Eswatini", label: <FormattedMessage id= "countries.SZ"/>},
  {value: "Ethiopia", label: <FormattedMessage id= "countries.ET"/>},
  {value: "Fiji", label: <FormattedMessage id= "countries.FJ"/>},
  {value: "Finland", label: <FormattedMessage id= "countries.FI"/>},
  {value: "France", label: <FormattedMessage id= "countries.FR"/>},
  {value: "Gabon", label: <FormattedMessage id= "countries.GA"/>},
  {value: "Gambia", label: <FormattedMessage id= "countries.GM"/>},
  {value: "Georgia", label: <FormattedMessage id= "countries.GE"/>},
  {value: "Germany", label: <FormattedMessage id= "countries.DE"/>},
  {value: "Ghana", label: <FormattedMessage id= "countries.GH"/>},
  {value: "Greece", label: <FormattedMessage id= "countries.GR"/>},
  {value: "Grenada", label: <FormattedMessage id= "countries.GD"/>},
  {value: "Guatemala", label: <FormattedMessage id= "countries.GT"/>},
  {value: "Guinea", label: <FormattedMessage id= "countries.GN"/>},
  {value: "Guinea-Bissau", label: <FormattedMessage id= "countries.GW"/>},
  {value: "Guyana", label: <FormattedMessage id= "countries.GY"/>},
  {value: "Haiti", label: <FormattedMessage id= "countries.HT"/>},
  {value: "Honduras", label: <FormattedMessage id= "countries.HN"/>},
  {value: "Hungary", label: <FormattedMessage id= "countries.HU"/>},
  {value: "Iceland", label: <FormattedMessage id= "countries.IS"/>},
  {value: "India", label: <FormattedMessage id= "countries.IN"/>},
  {value: "Indonesia", label: <FormattedMessage id= "countries.ID"/>},
  {value: "Iran (Islamic Republic of)", label: <FormattedMessage id= "countries.IR"/>},
  {value: "Iraq", label: <FormattedMessage id= "countries.IQ"/>},
  {value: "Ireland", label: <FormattedMessage id= "countries.IE"/>},
  {value: "Israel", label: <FormattedMessage id= "countries.IL"/>},
  {value: "Italy", label: <FormattedMessage id= "countries.IT"/>},
  {value: "Jamaica", label: <FormattedMessage id= "countries.JM"/>},
  {value: "Japan", label: <FormattedMessage id= "countries.JP"/>},
  {value: "Jordan", label: <FormattedMessage id= "countries.JO"/>},
  {value: "Kazakhstan", label: <FormattedMessage id= "countries.KZ"/>},
  {value: "Kenya", label: <FormattedMessage id= "countries.KE"/>},
  {value: "Kiribati", label: <FormattedMessage id= "countries.KI"/>},
  {value: "Korea (Democratic People's Republic of)", label: <FormattedMessage id= "countries.KP"/>},
  {value: "Korea, Republic of", label: <FormattedMessage id= "countries.KR"/>},
  {value: "Kuwait", label: <FormattedMessage id= "countries.KW"/>},
  {value: "Kyrgyzstan", label: <FormattedMessage id= "countries.KG"/>},
  {value: "Lao People's Democratic Republic", label: <FormattedMessage id= "countries.LA"/>},
  {value: "Latvia", label: <FormattedMessage id= "countries.LV"/>},
  {value: "Lebanon", label: <FormattedMessage id= "countries.LB"/>},
  {value: "Lesotho", label: <FormattedMessage id= "countries.LS"/>},
  {value: "Liberia", label: <FormattedMessage id= "countries.LR"/>},
  {value: "Libya", label: <FormattedMessage id= "countries.LY"/>},
  {value: "Liechtenstein", label: <FormattedMessage id= "countries.LI"/>},
  {value: "Lithuania", label: <FormattedMessage id= "countries.LT"/>},
  {value: "Luxembourg", label: <FormattedMessage id= "countries.LU"/>},
  {value: "Macedonia, the former Yugoslav Republic of", label: <FormattedMessage id= "countries.MK"/>},
  {value: "Madagascar", label: <FormattedMessage id= "countries.MG"/>},
  {value: "Malawi", label: <FormattedMessage id= "countries.MW"/>},
  {value: "Malaysia", label: <FormattedMessage id= "countries.MY"/>},
  {value: "Maldives", label: <FormattedMessage id= "countries.MV"/>},
  {value: "Mali", label: <FormattedMessage id= "countries.ML"/>},
  {value: "Malta", label: <FormattedMessage id= "countries.MT"/>},
  {value: "Marshall Islands", label: <FormattedMessage id= "countries.MH"/>},
  {value: "Mauritania", label: <FormattedMessage id= "countries.MR"/>},
  {value: "Mauritius", label: <FormattedMessage id= "countries.MU"/>},
  {value: "Mexico", label: <FormattedMessage id= "countries.MX"/>},
  {value: "Micronesia (Federated States of)", label: <FormattedMessage id= "countries.FM"/>},
  {value: "Moldova, Republic of", label: <FormattedMessage id= "countries.MD"/>},
  {value: "Monaco", label: <FormattedMessage id= "countries.MC"/>},
  {value: "Mongolia", label: <FormattedMessage id= "countries.MN"/>},
  {value: "Montenegro", label: <FormattedMessage id= "countries.ME"/>},
  {value: "Morocco", label: <FormattedMessage id= "countries.MA"/>},
  {value: "Mozambique", label: <FormattedMessage id= "countries.MZ"/>},
  {value: "Myanmar", label: <FormattedMessage id= "countries.MM"/>},
  {value: "Namibia", label: <FormattedMessage id= "countries.NA"/>},
  {value: "Nauru", label: <FormattedMessage id= "countries.NR"/>},
  {value: "Nepal", label: <FormattedMessage id= "countries.NP"/>},
  {value: "Netherlands", label: <FormattedMessage id= "countries.NL"/>},
  {value: "New Zealand", label: <FormattedMessage id= "countries.NZ"/>},
  {value: "Nicaragua", label: <FormattedMessage id= "countries.NI"/>},
  {value: "Niger", label: <FormattedMessage id= "countries.NE"/>},
  {value: "Nigeria", label: <FormattedMessage id= "countries.NG"/>},
  {value: "Norway", label: <FormattedMessage id= "countries.NO"/>},
  {value: "Oman", label: <FormattedMessage id= "countries.OM"/>},
  {value: "Pakistan", label: <FormattedMessage id= "countries.PK"/>},
  {value: "Palau", label: <FormattedMessage id= "countries.PW"/>},
  {value: "Panama", label: <FormattedMessage id= "countries.PA"/>},
  {value: "Papua New Guinea", label: <FormattedMessage id= "countries.PG"/>},
  {value: "Paraguay", label: <FormattedMessage id= "countries.PY"/>},
  {value: "Peru", label: <FormattedMessage id= "countries.PE"/>},
  {value: "Philippines", label: <FormattedMessage id= "countries.PH"/>},
  {value: "Poland", label: <FormattedMessage id= "countries.PL"/>},
  {value: "Portugal", label: <FormattedMessage id= "countries.PT"/>},
  {value: "Qatar", label: <FormattedMessage id= "countries.QA"/>},
  {value: "Romania", label: <FormattedMessage id= "countries.RO"/>},
  {value: "Russian Federation", label: <FormattedMessage id= "countries.RU"/>},
  {value: "Rwanda", label: <FormattedMessage id= "countries.RW"/>},
  {value: "Saint Kitts and Nevis", label: <FormattedMessage id= "countries.KN"/>},
  {value: "Saint Lucia", label: <FormattedMessage id= "countries.LC"/>},
  {value: "Saint Vincent and the Grenadines", label: <FormattedMessage id= "countries.VC"/>},
  {value: "Samoa", label: <FormattedMessage id= "countries.WS"/>},
  {value: "San Marino", label: <FormattedMessage id= "countries.SM"/>},
  {value: "Sao Tome and Principe", label: <FormattedMessage id= "countries.ST"/>},
  {value: "Saudi Arabia", label: <FormattedMessage id= "countries.SA"/>},
  {value: "Senegal", label: <FormattedMessage id= "countries.SN"/>},
  {value: "Serbia", label: <FormattedMessage id= "countries.RS"/>},
  {value: "Seychelles", label: <FormattedMessage id= "countries.SC"/>},
  {value: "Sierra Leone", label: <FormattedMessage id= "countries.SL"/>},
  {value: "Singapore", label: <FormattedMessage id= "countries.SG"/>},
  {value: "Slovakia", label: <FormattedMessage id= "countries.SK"/>},
  {value: "Slovenia", label: <FormattedMessage id= "countries.SI"/>},
  {value: "Solomon Islands", label: <FormattedMessage id= "countries.SB"/>},
  {value: "Somalia", label: <FormattedMessage id= "countries.SO"/>},
  {value: "South Africa", label: <FormattedMessage id= "countries.ZA"/>},
  {value: "South Sudan", label: <FormattedMessage id= "countries.SS"/>},
  {value: "Spain", label: <FormattedMessage id= "countries.ES"/>},
  {value: "Sri Lanka", label: <FormattedMessage id= "countries.LK"/>},
  {value: "Sudan", label: <FormattedMessage id= "countries.SD"/>},
  {value: "Suriname", label: <FormattedMessage id= "countries.SR"/>},
  {value: "Sweden", label: <FormattedMessage id= "countries.SE"/>},
  {value: "Switzerland", label: <FormattedMessage id= "countries.CH"/>},
  {value: "Syrian Arab Republic", label: <FormattedMessage id= "countries.SY"/>},
  {value: "Tajikistan", label: <FormattedMessage id= "countries.TJ"/>},
  {value: "Tanzania, United Republic of", label: <FormattedMessage id= "countries.TZ"/>},
  {value: "Thailand", label: <FormattedMessage id= "countries.TH"/>},
  {value: "Timor-Leste", label: <FormattedMessage id= "countries.TL"/>},
  {value: "Togo", label: <FormattedMessage id= "countries.TG"/>},
  {value: "Tonga", label: <FormattedMessage id= "countries.TO"/>},
  {value: "Trinidad and Tobago", label: <FormattedMessage id= "countries.TT"/>},
  {value: "Tunisia", label: <FormattedMessage id= "countries.TN"/>},
  {value: "Turkey", label: <FormattedMessage id= "countries.TR"/>},
  {value: "Turkmenistan", label: <FormattedMessage id= "countries.TM"/>},
  {value: "Tuvalu", label: <FormattedMessage id= "countries.TV"/>},
  {value: "Uganda", label: <FormattedMessage id= "countries.UG"/>},
  {value: "Ukraine", label: <FormattedMessage id= "countries.UA"/>},
  {value: "United Arab Emirates", label: <FormattedMessage id= "countries.AE"/>},
  {value: "United Kingdom of Great Britain and Northern Ireland", label: <FormattedMessage id= "countries.GB"/>},
  {value: "United States of America", label: <FormattedMessage id= "countries.US"/>},
  {value: "Uruguay", label: <FormattedMessage id= "countries.UY"/>},
  {value: "Uzbekistan", label: <FormattedMessage id= "countries.UZ"/>},
  {value: "Vanuatu", label: <FormattedMessage id= "countries.VU"/>},
  {value: "Venezuela (Bolivarian Republic of)", label: <FormattedMessage id= "countries.VE"/>},
  {value: "Viet Nam", label: <FormattedMessage id= "countries.VN"/>},
  {value: "Yemen", label: <FormattedMessage id= "countries.YE"/>},
  {value: "Zambia", label: <FormattedMessage id= "countries.ZM"/>},
  {value: "Zimbabwe", label: <FormattedMessage id= "countries.ZW"/>},
  ];

